name: build-book

on:
  workflow_call:
    inputs:
      environment_name:
        description: 'Name of conda environment to activate'
        required: false
        default: 'cookbook-dev'
        type: string
      environment_file:
        description: 'Name of conda environment file'
        required: false
        default: 'environment.yml'
        type: string
      path_to_notebooks:
        description: 'Location of the JupyterBook source relative to repo root'
        required: false
        default: './'
        type: string
      use_cached_environment:
        description: 'Flag for whether we should attempt to retrieve a previously cached environment.'
        required: false
        default: 'true'
        type: string  # had a lot of trouble with boolean types, see https://github.com/actions/runner/issues/1483

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files in repo
        uses: actions/checkout@main
      - name: remove Dockerfile
        run: |
          rm binder/Dockerfile
      - name: update jupyter dependencies with repo2docker
        uses: jupyterhub/repo2docker-action@master
        with: # make sure username & password/token matches your registry
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: "ghcr.io"
          PUBLIC_REGISTRY_CHECK: true
  build-book:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kmuehlbauer/erad2022:latest
      options: --user jovyan
    needs: [build-container]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3

#      - name: Setup Mambaforge
#        uses: conda-incubator/setup-miniconda@v2
#        with:
#          miniforge-variant: Mambaforge
#          miniforge-version: latest
#          activate-environment: ${{ inputs.environment_name }}
#          use-mamba: true

#      - name: Set cache date
#        if: ${{ inputs.use_cached_environment == 'true' }}
#        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

#      - uses: actions/cache@v3
#        if: inputs.use_cached_environment == 'true'
#        with:
#          path: /usr/share/miniconda3/envs/${{ inputs.environment_name }}
#          key: linux-64-conda-${{ hashFiles('${{ inputs.environment_file }}') }}-${{ env.DATE }}
#        id: cache

#      - name: Update environment
#        if: |
#          inputs.use_cached_environment != 'true'
#          || steps.cache.outputs.cache-hit != 'true'
#        run: mamba env update -n ${{ inputs.environment_name }} -f ${{ inputs.environment_file }}

#      - name: Install baltrad
#        run: |
#          set -x
#          set +e
#          export BALTRAD_INSTALL_ROOT=$PWD
#          bash -l $BALTRAD_INSTALL_ROOT/install/baltrad/install_baltrad.sh

      - name: Build the book
        run: |
          install/nbstripout_notebooks.sh
          jupyter-book build ${{ inputs.path_to_notebooks }}
      - name: Zip the book
        run: |
          set -x
          set -e
          if [ -f book.zip ]; then
              rm -rf book.zip
          fi
          zip -r book.zip ${{ inputs.path_to_notebooks }}/_build/html
      - name: Upload zipped book artifact
        uses: actions/upload-artifact@v3
        with:
          name: book-zip-${{github.event.number}}
          path: ./book.zip
